### PR TITLE
Update existing models

### PR DESCRIPTION
**Pull request by ieriii**
Hi :)

I've added a keyword argument _update_model_ to the _dedupe_dataframe_ function and rewritten some of the other internal functions to give the users the possibility to update an existing model, rather than training the model from scratch each time.

With the upgrade, users with an existing _training file.json_ can decide whether to train the model from scratch or, instead, import the _training_file.json_ and train the model a bit more (with same or additional data).

This is a feature wanted by some users, see [672](https://github.com/dedupeio/dedupe/issues/672) and [679](https://github.com/dedupeio/dedupe/issues/679).

I appreciate your time to review this request.
And thanks for creating this wrapper. I found it very useful.

Enrico

### CODE REVIEW

**Comment by Lyonk71** [comment]
@ieriii Cool fork, thanks for sharing! I'm super busy atm, but I'll try to review and approve this in the next few days.

**Comment by ieriii** [comment]
Thank you. Appreciated. :)

**Comment by Lyonk71** [comment]
Sorry for the delay. This is a mega awesome commit - thanks again for sharing!

**Comment by deepesch** [comment]
@ieriii Great commit Indeed. I read somewhere that 20 active learning labels are enough even for a complex dataset and more labels would lead to low recall. If we use this retraining let's say everyday. Would this mean ever increasing training file? Does this lead to more predicates hence lack of generalization for the model? Does this adjust commit adjust the existing weights?

**Comment by ieriii** [comment]
Thanks @deepesch.
I expect you'd update dedupe when you have a stream of data coming into your model.
Training your model with old and new data would allow the model to keep generalising well.

If you train your model with more data every day, I would expect the training file to become bigger and weights to be updated.

**Comment by deepesch** [comment]
What's the metric/framework do you use to decide the need for running update_model?

**Comment by ieriii** [comment]
Domain expertise can play an important part here. Especially if working with a stream of data.
I think it is important to explore the trend of new data coming in the model and decide upon it.

In case you want to rely on metrics:
- you can manually canonicalise a sample of data (i.e. create training data);
- run existing dedupe model on training data;
- check how many clusters you get compared to the cluster you manually create in your training data (metric1);
- calculate how many records have been correctly canonicalized in a confusion matrix fashion (metric2).

I think this can give you an indication of how the model reacts to new data and whether it needs updating.

**Pull request merged**
